steps:
  # Build the Docker image using the Docker Cloud Builder
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/carbon-cacao-401818/sampathraja-100900613/devops-lab2:$COMMIT_SHA', '.']

  # Push the image to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/carbon-cacao-401818/sampathraja-100900613/devops-lab2:$COMMIT_SHA']

#options:
  # Set logs bucket behavior to create a user-owned logs bucket in the same region as the build project
  #logging: REGIONAL_USER_OWNED_BUCKET
  

# options:
#   # Set logs bucket behavior to create a user-owned logs bucket in the same region as the build project
#   logging: 'febin-log'

images:
  - 'us-central1-docker.pkg.dev/carbon-cacao-401818/sampathraja-100900613/devops-lab2:$COMMIT_SHA'


